source("./functions.r")
Biological_process_module_UI<-function(id)
{
  ns<-NS(id)
  tagList(
    bscols(widths = 10,div(style="height: 15px;",width = '200px')),
    a("Click to be directed to Gene Ontology Consortium ", href="http://www.geneontology.org/", target="_blank"),
    bscols(widths = 10,div(style="height: 15px;",width = '200px')),
    fluidRow(column(10,DT::dataTableOutput(ns("Enriched_bp")))),
    downloadButton(ns('download_Enriched_BP_Table'), 'Download full Data'),
    DT::dataTableOutput(ns("filtered_BP")),
    uiOutput(ns("plot_option_bp")),
    uiOutput(ns("plot_category_bp")),
    uiOutput(ns("plot_category_go")),
    downloadButton(ns('download_bp_plot'), 'Download Plot'),
    plotOutput(ns("bp"))
  )
}

Biological_process_module<-function(input,output,session,DE_genes,
                                    organism,dds.fc,combination,wgcna_output)
{
  #Compute the GO terms based on a list for a list of DE genes(uses function enrichGO from clusterprofiler)
  #Construct  a matrix where row->comparison A vs B, C vs D .etc
  # columns (up regulated GO terms, down regulated GO terms)
  #Loop through a similar matrix generated by reactive DE_genes)
  #Filter GO terms for each element in the matrix generated by reactive DE_genes
  #enrichment analysis
  
  combo<-combination()
  print(combo())
  num<-length(combo())
  
  
Enriched_BP<-reactive({
    print("inside biological process line 39")
    print(organism())
    result<-DE_genes()
   
      if(!is.null(wgcna_output()))
      {
        if((length(wgcna_output()$modules())>0))
        {
          enrichment_main("biological process",result(),organism(),dds.fc(),
                          length(combo()),wgcna_output()$modules(),wgcna_output()$WGCNA_matrix(),NULL)
        }
      }
      else
      {
        print("inside biological process line 53")
        #print(head(result()))
        print(combination())
        print(unlist(combination()))
        combo<-combination()
        print(combo())
        num<-length(combo())
        print(combo())
        print(num)
        enrichment_main("biological process",result(),organism(),dds.fc(),
                        num,NULL,NULL,NULL)
      }
      
  })
  
  #Display summary of biological process
output$Enriched_bp <- DT::renderDataTable({
    
      result<-Enriched_BP()[[1]]
      
      print(result)
      
      #num <- length(input$combination)
      rows<-num
      modules<-NULL
      WGCNA_matrix<-NULL
      res<-NULL#data.frame(matrix(NA, nrow = num, ncol = 2))
      
      if(!is.null(wgcna_output()))
      {
        if((length(wgcna_output()$modules())>0))
        {
          modules<-as.data.frame(table(wgcna_output()$modules()))
          colnames(modules)<-c("Var1","number")
          
          entry<-c(as.vector(combo()), as.vector(modules$Var1))
          # print(modules$Var1)
          print(entry)
          rows<-length(entry)
          
          res<-data.frame(matrix(NA, nrow = rows, ncol = 3))
          colnames(res)<-c('Up regulated','Down regulated','Regulated')
          
          
          print(modules$Var1)
          #print(entry)
          rownames(res)<-lapply(1:rows, function(i) {
            unlist(entry[i])
            
          })
          
          for(i in 1:length(combo()))
          {
            #print(nrow(as.data.frame(result[[i]][1])))
            #print(head(result[[i]][[1]]))
            res[i,1]<-nrow(as.data.frame(result[[i]][[1]]))
            res[i,2]<-nrow(as.data.frame(result[[i]][[2]]))
            res[i,3]<-0
          }
          
          for(i in 1+length(combo()):nrow(modules))
          {
            #print(nrow(as.data.frame(result[[i]][1])))
            print('res')
            print(result[[i]][[3]])
            res[i,1:2]<-0
            res[i,3]<-nrow(as.data.frame(result[[i]][3]))
            
          }
        }
      }
      else
      {
        res<-data.frame(matrix(NA, nrow = length(combo()), ncol = 2))
        rownames(res)<-lapply(1:length(combo()), function(i) {
          #paste(combination()[[i]][1],' vs ',combination()[[i]][2])
          print(combo())
          #combo()[[i]]
          # if(num==1) combo()
          combo()[[i]]
          
        })
        colnames(res)<-c('Enriched BP for Up-reg genes','Enriched BP for Down-reg genes')
        print(res)
        print(res[1,1])
        for(i in 1:length(combo()))
        {
          print(nrow(as.data.frame(result[[i]][[1]])))
          res[i,1]<-nrow(as.data.frame(result[[i]][[1]]))
          res[i,2]<-nrow(as.data.frame(result[[i]][[2]]))
        }
        
      }
      
      print(res)
      DT::datatable(res,class = 'cell-border stripe',
                    selection = list(mode='single',target = 'cell'),
                    extensions = list('Scroller'=NULL,'Buttons'=NULL),
                    options = list(deferRender = TRUE,scrollX = TRUE,scrollY = 150,scroller = TRUE,dom = 'Bfrtip',
                                   buttons = list('copy', list(extend = 'collection',buttons = c('csv', 'excel', 'pdf'),
                                                               text = 'Download table'))),#I('colvis')
                    
                    escape = FALSE
      )
    
  })
  
  #Display GO terms for the selected comparison
  observeEvent(input$Enriched_bp_cell_clicked,{
    print('hey')
    print(input$Enriched_bp_cells_selected)
    print(input$Enriched_bp_cell_clicked)
    selected <- input$Enriched_bp_cells_selected
    row<-selected[1]
    print('row')
    print(row)
    col<-selected[2]
    print('col')
    print(col)
    if(length(selected)>0){
      
      output$filtered_BP <- DT::renderDataTable({
        print('hey')
        result<-Enriched_BP()[[1]]
        df<-as.data.frame(result[[row]][[col]])
        
        print(head(df))
        # genes<-df[,1]
        # df<-df[-1]
        # rownames(df)<-genes
        # df_final<- df[order(df$padj),]
        # colnames(df_final)[1]<-"Overall mean"
        # for (i in 7:length(colnames(df_final)))
        # {
        #   colnames(df_final)[i]<-paste(colnames(df_final)[i],"mean")
        # }
        DT::datatable(df,class = 'cell-border stripe',
                      selection = list(target = 'column'),
                      extensions = list('Scroller'=NULL,'Buttons'=NULL),
                      options = list(deferRender = TRUE,scrollX = TRUE,scrollY = 150,scroller = TRUE,dom = 'Bfrtip',
                                     buttons = list('copy', list(extend = 'collection',buttons = c('csv', 'excel', 'pdf'),
                                                                 text = 'Download only genes on clipboard'))))
        
        
        
      })
      #download button
      output$download_Enriched_BP_Table <- downloadHandler(
        
        filename = function() 
        {
          #condition<-paste(combination()[[row]][1],' vs ',combination()[[row]][2])
          condition <-combo()[[row]]
          if(col==1) paste('Up regulated BP for ',condition,'.xlsx')
          else if(col==2) paste('Down regulated BP for ',condition,'.xlsx')
          #else paste('All DE TF for ',condition,'.csv')
          #paste("DE genes for condition ",input$condition1," vs ",input$condition2,'.csv')
        },
        content = function(file) {
          #sort by adjusted p value.
          print('heyho')
          result<-Enriched_BP()[[1]]
          
          df<-as.data.frame(result[[row]][[col]])
          nam<-'Sheet1'
          condition <-combo()[[row]]
          condition<-str_replace_all(condition,"[^[:alnum:]]",".")
          if(col==1) nam<-paste('Up regulated BP for ',condition)
          else if(col==2) nam<-paste('Down regulated BP for ',condition)
          #write.csv(df, file)
          write.xlsx2(df, file, sheetName = nam,
                      col.names = TRUE, row.names = TRUE, append = FALSE)
          
        }
        
      )
      output$plot_option_bp<-renderUI({
        radioButtons(session$ns("plotType_bp"), "Plot Type:", choices = c("Barplot",# "Dotplot",
                                                              "Network plot","GO term plot"),selected = "Barplot")
      })
      
      output$plot_category_bp<-renderUI({
        textInput(session$ns("category_bp"),label = h6("Enter number of categories to display"), 
                  value = "10") 
      })
      output$plot_category_go<-renderUI({
        textInput(session$ns("category_go"),label = h6("Enter number of GO levels to display"), 
                  value = "") 
      })
      print(input$plotType_bp)
      print(as.numeric(input$category_bp))
      
      #Display boxplot of to 10 GO term of selected comparison
      bpplot<-reactive(
      {
        result<-Enriched_BP()[[2]] #obj
        res<-Enriched_BP()[[1]]
        #input$category
        #input$plot_k
        #enrichment input
        #category_go
        #input$plotType_bp (plot_type)
        #input$category_bp category
        req(input$category_bp)
        #req(input$plotType_bp)
        #req(input$category_go)
        enrichment_plot("biological process",result,res,row,col,input$category_bp,input$plotType_bp,input$category_go)
      })
        
      output$bp<- renderPlot({
        bpplot()
      })
      output$download_bp_plot <- downloadHandler(
        
        filename =function()
        {
          condition <-combo()[[row]]
          if(col==1) paste(input$plotType_bp,' of Up regulated BP for ',condition,'.pdf')
          else if(col==2) paste(input$plotType_bp,' of Down regulated BP for ',condition,'.pdf')
        },
        content = function(file) {
          #png(file)
          req(input$category_bp)
         # req(input$plotType_bp)
          #req(input$category_go)
          if(input$plotType_bp %in% c("Network plot","GO term plot"))
          {
            pdf(file)#,width=800, height=500) 
            bpplot()
            dev.off()
          }
          else
          {
            ggsave(file,bpplot())#,width=800, height=500)
          }
          
          #dev.off()
          
          
        })
    }
  })
  return(list(
    Enriched_BP_table=reactive({Enriched_BP()[[1]]}),
    Enriched_BP_obj=reactive({Enriched_BP()[[2]]})
  )
    
  )
}